import Head from 'next/head'
import ListOfPokemones from '../components/ListOfPokemones';
import NavBar from '../components/NavBar';
import get_pokemones from '../helpers/get_pokemones';
import styles from '../styles/Home.module.css'

export default function Home({ pokemones }) {

  const pokemones_data = JSON.parse(pokemones);
  return (
    <div>
      <Head>
        <title>PokeApi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <NavBar />
      <div className={styles.container}>
        <ListOfPokemones pokemones_data={pokemones_data} />
      </div>

    </div>
  )
}

export async function getServerSideProps() {
  const pokemones = await get_pokemones();

  return {
    props: {
      pokemones: JSON.stringify(pokemones)
    }
  }

}
